services:
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - "./credentials:/root/.aws"
      - "./cli_services:/usr/src/app/cli_services"
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-default}
